### ISSUE TITLE
Can't find the custom metadata

### ISSUE THREAD

**Issue by ronaldohoch** [pqina/filepond-plugin-file-metadata#1]
Hello!

I followed the website implementation but i can't find the metadata in the file.

On filepond's options:

```
    allowFileMetadata: true,
    fileMetadataObject: {
      'hello': 'world'
    },
```

**Comment by rikschennink** [comment]
Does `getMetadata('hello')` not return `'world'`?

**Comment by ronaldohoch** [comment]
I thought it would appear in the file properties list ...
